namespace AstroFinder
{
    public enum ListOrder
    {
        defaultorder,
        ascendingname,
        descendingname,
        ascendingstarname,
        descendingstarname,
        ascendingdiscoverymethod,
        descendingdiscoverymethod,
        ascendingdiscoveryyear,
        descendingdiscoveryyear,
        ascendingorbitalperiod,
        descendingorbitalperiod,
        ascendingplanetradius,
        descendingplanetradius,
        ascendingplanetmass,
        descendingplanetmass,
        ascendingplanettemperature,
        descendingplanettemperature,
        ascendingstellartemperature,
        descendingstellartemperature,
        ascendingstellarradius,
        descendingstellarradius,
        ascendingstellarmass,
        descendingstellarmass,
        ascendingstellarage,
        descendingstellarage,
        ascendingstellarrotationvelocity,
        descendingstellarrotationvelocity,
        ascendingstellarrotationperiod,
        descendingstellarrotationperiod,
        ascendingdistance,
        descendingdistance,
        ascendingchildplanets,
        descendingchildplanets
    }
}
